//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> MaximumExam { get; set; }
        public Nullable<int> MaximumClass { get; set; }
        public string Code { get; set; }
        public string MISFileID { get; set; }
    }
}
