//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTK
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CTKDB_NMEntities : DbContext
    {
        public CTKDB_NMEntities()
            : base("name=CTKDB_NMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BARCODE> BARCODE { get; set; }
        public virtual DbSet<Courses> Courses { get; set; }
        public virtual DbSet<Master> Master { get; set; }
        public virtual DbSet<ResultStatus> ResultStatus { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<VER> VER { get; set; }
    }
}
