//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master
    {
        public long ID { get; set; }
        public string CourseID { get; set; }
        public string StudentID { get; set; }
        public Nullable<int> ExamMark { get; set; }
        public string SSID { get; set; }
        public string Status { get; set; }
        public string MISID { get; set; }
    }
}
