//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public string Class { get; set; }
        public string AcademicYear { get; set; }
        public string StudentID { get; set; }
        public string AcademicClass { get; set; }
    }
}
