//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTK
{
    using System;
    using System.Collections.Generic;
    
    public partial class VER
    {
        public int Id { get; set; }
        public int Major { get; set; }
        public int Minor { get; set; }
    }
}
