//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace CTK.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CTKDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CTKDBEntities object using the connection string found in the 'CTKDBEntities' section of the application configuration file.
        /// </summary>
        public CTKDBEntities() : base("name=CTKDBEntities", "CTKDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CTKDBEntities object.
        /// </summary>
        public CTKDBEntities(string connectionString) : base(connectionString, "CTKDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CTKDBEntities object.
        /// </summary>
        public CTKDBEntities(EntityConnection connection) : base(connection, "CTKDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Courses> Courses
        {
            get
            {
                if ((_Courses == null))
                {
                    _Courses = base.CreateObjectSet<Courses>("Courses");
                }
                return _Courses;
            }
        }
        private ObjectSet<Courses> _Courses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Master> Master
        {
            get
            {
                if ((_Master == null))
                {
                    _Master = base.CreateObjectSet<Master>("Master");
                }
                return _Master;
            }
        }
        private ObjectSet<Master> _Master;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Students> Students
        {
            get
            {
                if ((_Students == null))
                {
                    _Students = base.CreateObjectSet<Students>("Students");
                }
                return _Students;
            }
        }
        private ObjectSet<Students> _Students;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Courses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCourses(Courses courses)
        {
            base.AddObject("Courses", courses);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Master EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMaster(Master master)
        {
            base.AddObject("Master", master);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Students EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStudents(Students students)
        {
            base.AddObject("Students", students);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CTKDBModel", Name="Courses")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Courses : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Courses object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Courses CreateCourses(global::System.Int64 id)
        {
            Courses courses = new Courses();
            courses.ID = id;
            return courses;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MaximumExam
        {
            get
            {
                return _MaximumExam;
            }
            set
            {
                OnMaximumExamChanging(value);
                ReportPropertyChanging("MaximumExam");
                _MaximumExam = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaximumExam");
                OnMaximumExamChanged();
            }
        }
        private Nullable<global::System.Int32> _MaximumExam;
        partial void OnMaximumExamChanging(Nullable<global::System.Int32> value);
        partial void OnMaximumExamChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MaximumClass
        {
            get
            {
                return _MaximumClass;
            }
            set
            {
                OnMaximumClassChanging(value);
                ReportPropertyChanging("MaximumClass");
                _MaximumClass = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaximumClass");
                OnMaximumClassChanged();
            }
        }
        private Nullable<global::System.Int32> _MaximumClass;
        partial void OnMaximumClassChanging(Nullable<global::System.Int32> value);
        partial void OnMaximumClassChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CTKDBModel", Name="Master")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Master : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Master object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Master CreateMaster(global::System.Int64 id)
        {
            Master master = new Master();
            master.ID = id;
            return master;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CourseID
        {
            get
            {
                return _CourseID;
            }
            set
            {
                OnCourseIDChanging(value);
                ReportPropertyChanging("CourseID");
                _CourseID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CourseID");
                OnCourseIDChanged();
            }
        }
        private global::System.String _CourseID;
        partial void OnCourseIDChanging(global::System.String value);
        partial void OnCourseIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StudentID
        {
            get
            {
                return _StudentID;
            }
            set
            {
                OnStudentIDChanging(value);
                ReportPropertyChanging("StudentID");
                _StudentID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StudentID");
                OnStudentIDChanged();
            }
        }
        private global::System.String _StudentID;
        partial void OnStudentIDChanging(global::System.String value);
        partial void OnStudentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ExamMark
        {
            get
            {
                return _ExamMark;
            }
            set
            {
                OnExamMarkChanging(value);
                ReportPropertyChanging("ExamMark");
                _ExamMark = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExamMark");
                OnExamMarkChanged();
            }
        }
        private Nullable<global::System.Int32> _ExamMark;
        partial void OnExamMarkChanging(Nullable<global::System.Int32> value);
        partial void OnExamMarkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SSID
        {
            get
            {
                return _SSID;
            }
            set
            {
                OnSSIDChanging(value);
                ReportPropertyChanging("SSID");
                _SSID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SSID");
                OnSSIDChanged();
            }
        }
        private global::System.String _SSID;
        partial void OnSSIDChanging(global::System.String value);
        partial void OnSSIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CTKDBModel", Name="Students")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Students : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Students object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Students CreateStudents(global::System.Int64 id)
        {
            Students students = new Students();
            students.ID = id;
            return students;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Class
        {
            get
            {
                return _Class;
            }
            set
            {
                OnClassChanging(value);
                ReportPropertyChanging("AcademicClass");
                _Class = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AcademicClass");
                OnClassChanged();
            }
        }
        private global::System.String _Class;
        partial void OnClassChanging(global::System.String value);
        partial void OnClassChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AcademicYear
        {
            get
            {
                return _AcademicYear;
            }
            set
            {
                OnAcademicYearChanging(value);
                ReportPropertyChanging("AcademicYear");
                _AcademicYear = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AcademicYear");
                OnAcademicYearChanged();
            }
        }
        private global::System.String _AcademicYear;
        partial void OnAcademicYearChanging(global::System.String value);
        partial void OnAcademicYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StudentID
        {
            get
            {
                return _StudentID;
            }
            set
            {
                OnStudentIDChanging(value);
                ReportPropertyChanging("StudentID");
                _StudentID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StudentID");
                OnStudentIDChanged();
            }
        }
        private global::System.String _StudentID;
        partial void OnStudentIDChanging(global::System.String value);
        partial void OnStudentIDChanged();

        #endregion
    
    }

    #endregion
    
}
